# Dependabot version updates.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/projects/ccc-ui'
    schedule:
      interval: 'weekly'
    groups:
      go-dependencies:
        patterns:
          - '*'
  - package-ecosystem: 'npm'
    directory: '/projects/ccc-auth'
    schedule:
      interval: 'weekly'
    groups:
      go-dependencies:
        patterns:
          - '*'
