// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/cccteam/session (interfaces: PasswordAuthHandlers)
//
// Generated by this command:
//
//	mockgen -package=mock_router -destination=../../pkg/mock/mock_router_password_auth/mock_password_auth_handlers.go github.com/cccteam/session PasswordAuthHandlers
//

// Package mock_router is a generated GoMock package.
package mock_router

import (
	http "net/http"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPasswordAuthHandlers is a mock of PasswordAuthHandlers interface.
type MockPasswordAuthHandlers struct {
	ctrl     *gomock.Controller
	recorder *MockPasswordAuthHandlersMockRecorder
	isgomock struct{}
}

// MockPasswordAuthHandlersMockRecorder is the mock recorder for MockPasswordAuthHandlers.
type MockPasswordAuthHandlersMockRecorder struct {
	mock *MockPasswordAuthHandlers
}

// NewMockPasswordAuthHandlers creates a new mock instance.
func NewMockPasswordAuthHandlers(ctrl *gomock.Controller) *MockPasswordAuthHandlers {
	mock := &MockPasswordAuthHandlers{ctrl: ctrl}
	mock.recorder = &MockPasswordAuthHandlersMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPasswordAuthHandlers) EXPECT() *MockPasswordAuthHandlersMockRecorder {
	return m.recorder
}

// ActivateUser mocks base method.
func (m *MockPasswordAuthHandlers) ActivateUser() http.HandlerFunc {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ActivateUser")
	ret0, _ := ret[0].(http.HandlerFunc)
	return ret0
}

// ActivateUser indicates an expected call of ActivateUser.
func (mr *MockPasswordAuthHandlersMockRecorder) ActivateUser() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ActivateUser", reflect.TypeOf((*MockPasswordAuthHandlers)(nil).ActivateUser))
}

// Authenticated mocks base method.
func (m *MockPasswordAuthHandlers) Authenticated() http.HandlerFunc {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Authenticated")
	ret0, _ := ret[0].(http.HandlerFunc)
	return ret0
}

// Authenticated indicates an expected call of Authenticated.
func (mr *MockPasswordAuthHandlersMockRecorder) Authenticated() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Authenticated", reflect.TypeOf((*MockPasswordAuthHandlers)(nil).Authenticated))
}

// ChangeUserPassword mocks base method.
func (m *MockPasswordAuthHandlers) ChangeUserPassword() http.HandlerFunc {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangeUserPassword")
	ret0, _ := ret[0].(http.HandlerFunc)
	return ret0
}

// ChangeUserPassword indicates an expected call of ChangeUserPassword.
func (mr *MockPasswordAuthHandlersMockRecorder) ChangeUserPassword() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeUserPassword", reflect.TypeOf((*MockPasswordAuthHandlers)(nil).ChangeUserPassword))
}

// ChangeUsername mocks base method.
func (m *MockPasswordAuthHandlers) ChangeUsername() http.HandlerFunc {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangeUsername")
	ret0, _ := ret[0].(http.HandlerFunc)
	return ret0
}

// ChangeUsername indicates an expected call of ChangeUsername.
func (mr *MockPasswordAuthHandlersMockRecorder) ChangeUsername() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeUsername", reflect.TypeOf((*MockPasswordAuthHandlers)(nil).ChangeUsername))
}

// CreateUser mocks base method.
func (m *MockPasswordAuthHandlers) CreateUser() http.HandlerFunc {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser")
	ret0, _ := ret[0].(http.HandlerFunc)
	return ret0
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockPasswordAuthHandlersMockRecorder) CreateUser() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockPasswordAuthHandlers)(nil).CreateUser))
}

// DeactivateUser mocks base method.
func (m *MockPasswordAuthHandlers) DeactivateUser() http.HandlerFunc {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeactivateUser")
	ret0, _ := ret[0].(http.HandlerFunc)
	return ret0
}

// DeactivateUser indicates an expected call of DeactivateUser.
func (mr *MockPasswordAuthHandlersMockRecorder) DeactivateUser() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeactivateUser", reflect.TypeOf((*MockPasswordAuthHandlers)(nil).DeactivateUser))
}

// DeleteUser mocks base method.
func (m *MockPasswordAuthHandlers) DeleteUser() http.HandlerFunc {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser")
	ret0, _ := ret[0].(http.HandlerFunc)
	return ret0
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockPasswordAuthHandlersMockRecorder) DeleteUser() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockPasswordAuthHandlers)(nil).DeleteUser))
}

// Login mocks base method.
func (m *MockPasswordAuthHandlers) Login() http.HandlerFunc {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login")
	ret0, _ := ret[0].(http.HandlerFunc)
	return ret0
}

// Login indicates an expected call of Login.
func (mr *MockPasswordAuthHandlersMockRecorder) Login() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockPasswordAuthHandlers)(nil).Login))
}

// Logout mocks base method.
func (m *MockPasswordAuthHandlers) Logout() http.HandlerFunc {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logout")
	ret0, _ := ret[0].(http.HandlerFunc)
	return ret0
}

// Logout indicates an expected call of Logout.
func (mr *MockPasswordAuthHandlersMockRecorder) Logout() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logout", reflect.TypeOf((*MockPasswordAuthHandlers)(nil).Logout))
}

// SetXSRFToken mocks base method.
func (m *MockPasswordAuthHandlers) SetXSRFToken(next http.Handler) http.Handler {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetXSRFToken", next)
	ret0, _ := ret[0].(http.Handler)
	return ret0
}

// SetXSRFToken indicates an expected call of SetXSRFToken.
func (mr *MockPasswordAuthHandlersMockRecorder) SetXSRFToken(next any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetXSRFToken", reflect.TypeOf((*MockPasswordAuthHandlers)(nil).SetXSRFToken), next)
}

// StartSession mocks base method.
func (m *MockPasswordAuthHandlers) StartSession(next http.Handler) http.Handler {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartSession", next)
	ret0, _ := ret[0].(http.Handler)
	return ret0
}

// StartSession indicates an expected call of StartSession.
func (mr *MockPasswordAuthHandlersMockRecorder) StartSession(next any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartSession", reflect.TypeOf((*MockPasswordAuthHandlers)(nil).StartSession), next)
}

// ValidateSession mocks base method.
func (m *MockPasswordAuthHandlers) ValidateSession(next http.Handler) http.Handler {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateSession", next)
	ret0, _ := ret[0].(http.Handler)
	return ret0
}

// ValidateSession indicates an expected call of ValidateSession.
func (mr *MockPasswordAuthHandlersMockRecorder) ValidateSession(next any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateSession", reflect.TypeOf((*MockPasswordAuthHandlers)(nil).ValidateSession), next)
}

// ValidateXSRFToken mocks base method.
func (m *MockPasswordAuthHandlers) ValidateXSRFToken(next http.Handler) http.Handler {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateXSRFToken", next)
	ret0, _ := ret[0].(http.Handler)
	return ret0
}

// ValidateXSRFToken indicates an expected call of ValidateXSRFToken.
func (mr *MockPasswordAuthHandlersMockRecorder) ValidateXSRFToken(next any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateXSRFToken", reflect.TypeOf((*MockPasswordAuthHandlers)(nil).ValidateXSRFToken), next)
}
