// Code generated by MockGen. DO NOT EDIT.
// Source: ../../pkg/routerpasswordauth/router.go
//
// Generated by this command:
//
//	mockgen -package=mock_router -source ../../pkg/routerpasswordauth/router.go -destination ../../pkg/mock/mock_router_password_auth/mock_handlers.go
//

// Package mock_router is a generated GoMock package.
package mock_router

import (
	http "net/http"
	reflect "reflect"

	session "github.com/cccteam/session"
	gomock "go.uber.org/mock/gomock"
)

// MockHandlers is a mock of Handlers interface.
type MockHandlers struct {
	ctrl     *gomock.Controller
	recorder *MockHandlersMockRecorder
	isgomock struct{}
}

// MockHandlersMockRecorder is the mock recorder for MockHandlers.
type MockHandlersMockRecorder struct {
	mock *MockHandlers
}

// NewMockHandlers creates a new mock instance.
func NewMockHandlers(ctrl *gomock.Controller) *MockHandlers {
	mock := &MockHandlers{ctrl: ctrl}
	mock.recorder = &MockHandlersMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHandlers) EXPECT() *MockHandlersMockRecorder {
	return m.recorder
}

// Assets mocks base method.
func (m *MockHandlers) Assets() http.HandlerFunc {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Assets")
	ret0, _ := ret[0].(http.HandlerFunc)
	return ret0
}

// Assets indicates an expected call of Assets.
func (mr *MockHandlersMockRecorder) Assets() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Assets", reflect.TypeOf((*MockHandlers)(nil).Assets))
}

// CompressionMiddleware mocks base method.
func (m *MockHandlers) CompressionMiddleware() func(http.Handler) http.Handler {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompressionMiddleware")
	ret0, _ := ret[0].(func(http.Handler) http.Handler)
	return ret0
}

// CompressionMiddleware indicates an expected call of CompressionMiddleware.
func (mr *MockHandlersMockRecorder) CompressionMiddleware() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompressionMiddleware", reflect.TypeOf((*MockHandlers)(nil).CompressionMiddleware))
}

// DeepLink mocks base method.
func (m *MockHandlers) DeepLink(next http.Handler) http.Handler {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeepLink", next)
	ret0, _ := ret[0].(http.Handler)
	return ret0
}

// DeepLink indicates an expected call of DeepLink.
func (mr *MockHandlersMockRecorder) DeepLink(next any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeepLink", reflect.TypeOf((*MockHandlers)(nil).DeepLink), next)
}

// LoggerMiddleware mocks base method.
func (m *MockHandlers) LoggerMiddleware() func(http.Handler) http.Handler {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoggerMiddleware")
	ret0, _ := ret[0].(func(http.Handler) http.Handler)
	return ret0
}

// LoggerMiddleware indicates an expected call of LoggerMiddleware.
func (mr *MockHandlersMockRecorder) LoggerMiddleware() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoggerMiddleware", reflect.TypeOf((*MockHandlers)(nil).LoggerMiddleware))
}

// Login mocks base method.
func (m *MockHandlers) Login() http.HandlerFunc {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login")
	ret0, _ := ret[0].(http.HandlerFunc)
	return ret0
}

// Login indicates an expected call of Login.
func (mr *MockHandlersMockRecorder) Login() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockHandlers)(nil).Login))
}

// NoCaching mocks base method.
func (m *MockHandlers) NoCaching(next http.Handler) http.Handler {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NoCaching", next)
	ret0, _ := ret[0].(http.Handler)
	return ret0
}

// NoCaching indicates an expected call of NoCaching.
func (mr *MockHandlersMockRecorder) NoCaching(next any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NoCaching", reflect.TypeOf((*MockHandlers)(nil).NoCaching), next)
}

// PatchResources mocks base method.
func (m *MockHandlers) PatchResources() http.HandlerFunc {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PatchResources")
	ret0, _ := ret[0].(http.HandlerFunc)
	return ret0
}

// PatchResources indicates an expected call of PatchResources.
func (mr *MockHandlersMockRecorder) PatchResources() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PatchResources", reflect.TypeOf((*MockHandlers)(nil).PatchResources))
}

// PostPayments mocks base method.
func (m *MockHandlers) PostPayments() http.HandlerFunc {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PostPayments")
	ret0, _ := ret[0].(http.HandlerFunc)
	return ret0
}

// PostPayments indicates an expected call of PostPayments.
func (mr *MockHandlersMockRecorder) PostPayments() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostPayments", reflect.TypeOf((*MockHandlers)(nil).PostPayments))
}

// SecurityHeaders mocks base method.
func (m *MockHandlers) SecurityHeaders(next http.Handler) http.Handler {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SecurityHeaders", next)
	ret0, _ := ret[0].(http.Handler)
	return ret0
}

// SecurityHeaders indicates an expected call of SecurityHeaders.
func (mr *MockHandlersMockRecorder) SecurityHeaders(next any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SecurityHeaders", reflect.TypeOf((*MockHandlers)(nil).SecurityHeaders), next)
}

// Session mocks base method.
func (m *MockHandlers) Session() session.PasswordAuthHandlers {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Session")
	ret0, _ := ret[0].(session.PasswordAuthHandlers)
	return ret0
}

// Session indicates an expected call of Session.
func (mr *MockHandlersMockRecorder) Session() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Session", reflect.TypeOf((*MockHandlers)(nil).Session))
}

// User mocks base method.
func (m *MockHandlers) User() http.HandlerFunc {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "User")
	ret0, _ := ret[0].(http.HandlerFunc)
	return ret0
}

// User indicates an expected call of User.
func (mr *MockHandlersMockRecorder) User() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "User", reflect.TypeOf((*MockHandlers)(nil).User))
}

// Users mocks base method.
func (m *MockHandlers) Users() http.HandlerFunc {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Users")
	ret0, _ := ret[0].(http.HandlerFunc)
	return ret0
}

// Users indicates an expected call of Users.
func (mr *MockHandlersMockRecorder) Users() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Users", reflect.TypeOf((*MockHandlers)(nil).Users))
}

// Weather mocks base method.
func (m *MockHandlers) Weather() http.HandlerFunc {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Weather")
	ret0, _ := ret[0].(http.HandlerFunc)
	return ret0
}

// Weather indicates an expected call of Weather.
func (mr *MockHandlersMockRecorder) Weather() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Weather", reflect.TypeOf((*MockHandlers)(nil).Weather))
}

// Weathers mocks base method.
func (m *MockHandlers) Weathers() http.HandlerFunc {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Weathers")
	ret0, _ := ret[0].(http.HandlerFunc)
	return ret0
}

// Weathers indicates an expected call of Weathers.
func (mr *MockHandlersMockRecorder) Weathers() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Weathers", reflect.TypeOf((*MockHandlers)(nil).Weathers))
}

// WithParamsHTTP mocks base method.
func (m *MockHandlers) WithParamsHTTP() func(http.Handler) http.Handler {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithParamsHTTP")
	ret0, _ := ret[0].(func(http.Handler) http.Handler)
	return ret0
}

// WithParamsHTTP indicates an expected call of WithParamsHTTP.
func (mr *MockHandlersMockRecorder) WithParamsHTTP() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithParamsHTTP", reflect.TypeOf((*MockHandlers)(nil).WithParamsHTTP))
}
