name: CI
on:
  pull_request:
    types: [opened, synchronize, reopened] # these are the defaults - synchronize means 'commits pushed to PR'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  closes-issue-check:
    uses: cccteam/github-workflows/.github/workflows/closes-issue-check.yml@v4.1.0

  angular:
    name: Run angular checks
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./gui
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint

      - name: Run build
        run: npm run build
