name: Release Please

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions: {}

jobs:
  release-please:
    permissions:
      contents: write
      pull-requests: write
    uses: cccteam/github-workflows/.github/workflows/release-please.yml@952f1cfc7e41019f9afe4b43817aa9dec9d9f92f # v6.1.1
    secrets:
      RELEASE_PLEASE_APP_ID: ${{ secrets.RELEASE_PLEASE_APP_ID }}
      RELEASE_PLEASE_APP_PEM: ${{ secrets.RELEASE_PLEASE_APP_PEM }}

  npm-publish:
    needs: release-please
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'

      - run: npm install -g npm@latest
      - run: npm ci
      - run: npm run build --if-present
      - run: npm publish --access public
        working-directory: ./dist/ccc-lib
